# Post-Provision Script for devShop Application
# This script runs after Azure infrastructure is provisioned
# It configures the SQL Server database and prepares the environment

[CmdletBinding()]
param()

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  devShop Post-Provision Configuration" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Get environment variables from azd
$sqlServerIp = $env:SQL_SERVER_PRIVATE_IP
$sqlAdminUser = $env:SQL_ADMIN_USERNAME
$sqlAdminPass = $env:SQL_ADMIN_PASSWORD
$storageAccount = $env:STORAGE_ACCOUNT_NAME
$resourceGroup = $env:AZURE_RESOURCE_GROUP

if (-not $sqlServerIp -or -not $sqlAdminUser -or -not $sqlAdminPass) {
    Write-Host "ERROR: Required environment variables not set." -ForegroundColor Red
    Write-Host "Make sure azd provision has completed successfully." -ForegroundColor Red
    exit 1
}

Write-Host "[1/4] Uploading setup scripts to Azure Storage..." -ForegroundColor Yellow

# Upload database scripts to storage account
$scriptsPath = Join-Path $PSScriptRoot ".." "database"
$setupIisPath = Join-Path $PSScriptRoot "setup-iis.ps1"

try {
    # Upload database setup scripts
    az storage blob upload `
        --account-name $storageAccount `
        --container-name scripts `
        --name CreateTables.sql `
        --file (Join-Path $scriptsPath "CreateTables.sql") `
        --auth-mode login `
        --overwrite

    az storage blob upload `
        --account-name $storageAccount `
        --container-name scripts `
        --name PopulateTables.sql `
        --file (Join-Path $scriptsPath "PopulateTables.sql") `
        --auth-mode login `
        --overwrite

    # Upload IIS setup script
    az storage blob upload `
        --account-name $storageAccount `
        --container-name scripts `
        --name setup-iis.ps1 `
        --file $setupIisPath `
        --auth-mode login `
        --overwrite

    Write-Host "   Scripts uploaded successfully." -ForegroundColor Green
} catch {
    Write-Host "   WARNING: Failed to upload scripts: $_" -ForegroundColor Yellow
    Write-Host "   You may need to upload scripts manually." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "[2/4] Configuring SQL Server database..." -ForegroundColor Yellow

# Connection string for SQL Server
$connectionString = "Server=$sqlServerIp;Database=master;User Id=$sqlAdminUser;Password=$sqlAdminPass;TrustServerCertificate=True;"

Write-Host "   Connecting to SQL Server at $sqlServerIp..." -ForegroundColor Gray

# Create database
$createDbSql = @"
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'devShopDB')
BEGIN
    CREATE DATABASE devShopDB;
    PRINT 'Database devShopDB created successfully.';
END
ELSE
BEGIN
    PRINT 'Database devShopDB already exists.';
END
"@

try {
    # Try to execute SQL using sqlcmd if available
    $createDbSql | sqlcmd -S $sqlServerIp -U $sqlAdminUser -P $sqlAdminPass -d master -b
    Write-Host "   Database created successfully." -ForegroundColor Green
} catch {
    Write-Host "   WARNING: Could not create database automatically." -ForegroundColor Yellow
    Write-Host "   SQL Server may still be initializing or sqlcmd is not available." -ForegroundColor Yellow
    Write-Host "   You can run database\Setup-Database.ps1 manually later." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "[3/4] Setting up application configuration..." -ForegroundColor Yellow

# Create .env file for local development
$envFilePath = Join-Path $PSScriptRoot ".." ".env"
$envContent = @"
# devShop Environment Variables (generated by azd)
SQL_SERVER_PRIVATE_IP=$sqlServerIp
SQL_ADMIN_USERNAME=$sqlAdminUser
SQL_ADMIN_PASSWORD=$sqlAdminPass
CONNECTION_STRING=Server=$sqlServerIp;Database=devShopDB;User Id=$sqlAdminUser;Password=$sqlAdminPass;TrustServerCertificate=True;
"@

Set-Content -Path $envFilePath -Value $envContent
Write-Host "   Environment file created: .env" -ForegroundColor Green

Write-Host ""
Write-Host "[4/4] Deployment summary..." -ForegroundColor Yellow
Write-Host ""
Write-Host "   SQL Server IP  : $sqlServerIp" -ForegroundColor Cyan
Write-Host "   SQL Admin User : $sqlAdminUser" -ForegroundColor Cyan
Write-Host "   Web Server URL : $env:WEB_URL" -ForegroundColor Cyan
Write-Host ""

Write-Host "========================================" -ForegroundColor Green
Write-Host "  Post-Provision Completed!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor White
Write-Host "  1. Wait 5-10 minutes for VMs to complete setup" -ForegroundColor Gray
Write-Host "  2. Run: azd deploy" -ForegroundColor Gray
Write-Host "  3. Access your app at: $env:WEB_URL" -ForegroundColor Gray
Write-Host ""
